var1= float(input("Jefe cuanto pesas?"))
var2= float(input("Jefe cuanto mides?"))
imc= (var1 / (var2)**2)
imcRound= round(imc, 2)
print("Tu indice de masa corporal es ", imc ," donde ", imcRound ," es el indie de masa corporal calculado redondeando los dos decimales")
